import React from 'react';
import './Resume.css';

const Resume = ({ details }) => {
  return (
    <div className="resume-container">
      <div className="header">
        <div className="name">{details.name}</div>
        <div className="contact-info">{details.email} | {details.phone}</div>
      </div>

      <div className="section">
        <div className="section-title">Summary</div>
        <div className="section-content">{details.summary}</div>
      </div>

      <div className="section">
        <div className="section-title">Experience</div>
        <div className="section-content">
          {details.experience.map((exp, index) => (
            <div key={index}>
              <div><strong>{exp.title}</strong></div>
              <div>{exp.company}, {exp.location}</div>
              <div>{exp.startDate} - {exp.endDate}</div>
              <div>{exp.description}</div>
            </div>
          ))}
        </div>
      </div>

      <div className="section">
        <div className="section-title">Education</div>
        <div className="section-content">
          {details.education.map((edu, index) => (
            <div key={index}>
              <div><strong>{edu.degree}</strong></div>
              <div>{edu.school}, {edu.location}</div>
              <div>{edu.graduationDate}</div>
            </div>
          ))}
        </div>
      </div>

      <div className="section">
        <div className="section-title">Skills</div>
        <div className="section-content skills">
          {details.skills.map((skill, index) => (
            <span key={index} className="skill-item">{skill}</span>
          ))}
        </div>
      </div>

      <div className="footer">Generated by Resume Builder App</div>
    </div>
  );
};

export default Resume;
